# COGS 108 - Data Checkpoint

# Names

- Sebastian Algharaballi (A16314698)
- Kenneth Hogan (A16404864)
- Evan Liu (A16675674)
- Lauren Lui (A16657998)
- Aarohi Zade (A16222196)

<a id='research_question'></a>
# Research Question

“Is there a correlation between the liveliness (as measured by BPM, valence, and energy) of the top 50 Spotify songs in the United States per month from 2010-2022 and economic prosperity of the US population (as measured by country-wide consumer confidence)?”

# Datasets

- __Dataset Name__: Top Spotify Songs from 2010-2019 - BY YEAR
- __Link to the dataset__: https://www.kaggle.com/datasets/leonardopena/top-spotify-songs-from-20102019-by-year
- __Number of observations__: 603

This dataset serves to provide a list of the most-streamed songs on Spotify from the years of 2010 to 2019. In addition to listing the aforementioned songs in order of the number of times they were streamed in their respective years, the dataset also includes various metrics for each song with a variety of implications for exploratory data analysis. For the purposes of this and all other Spotify datasets used in this analysis, the metrics being considered are:

> -  __Title__: Name of the Track
> -  __Artist__: Name of the Track's Vocalist
> -  __Year__: The year the track was appeared in the top 50 charts
> -  __BPM__: The number of beats per minute associated with the track
> -  __Valence__: The measure of positive mood of the track. High valence is correlated with high positivity.
> -  __Energy__: The measure of the vivacity of the track. High energy is correlated with high vivacity.

The dataset lists the most-streamed songs for each year in order of popularity, but lists varying numbers of songs per year. In the course of our data cleaning, the dataset is filtered to only contain the 50 most popular songs from each year, and both the valence and energy ratings of each song are normalized to fall between 0 and 1.

- __Dataset Name__: Top Hits Spotify from 2000-2019
- __Link to the dataset__: https://www.kaggle.com/datasets/paradisejoy/top-hits-spotify-from-20002019
- __Number of observations__: 2000 originally, filtered to 300

This dataset also contains a summative list of the most-streamed songs on Spotify from the years of 2010 to 2019, albeit with certain years that have more songs than the aforementioned dataset. For the purposes of this analysis, the dataset contains a list of the top 50 songs from 2012, as the earlier dataset did not possess at least 50 songs for the year of 2022.

- __Dataset Name__: Top 50 Spotify Songs - 2019
- __Link to the dataset__: https://www.kaggle.com/datasets/leonardopena/top50spotify2019
- __Number of observations__: 50

This dataset contains a summative list of the most-streamed songs on Spotify during the year of 2019. The original 2019 sample from the 2010-2019 dataset possessed less than 50 rows of data, so this dataset was used to provide the necessary 50 songs.

- __Dataset Name__: Top 50 Spotify Tracks - 2020
- __Link to the dataset__: https://www.kaggle.com/datasets/atillacolak/top-50-spotify-tracks-2020
- __Number of observations__: 50

This dataset contains a summative list of the most-streamed songs on Spotify during the year of 2020. The original 2012-2019 dataset did not have data beyond 2019, so this dataset was used to provide additional insight in our analysis in tandem with the consumer confidence data detailed below.

- __Dataset Name__: Spotify Top 50 Songs in 2021
- __Link to the dataset__: https://www.kaggle.com/datasets/equinxx/spotify-top-50-songs-in-2021
- __Number of observations__: 50

This dataset contains a summative list of the most-streamed songs on Spotify during the year of 2021. The original 2012-2019 dataset did not have data beyond 2019, so this dataset was used to provide additional insight in our analysis in tandem with the consumer confidence data detailed below.

- __Dataset Name__: Spotify 2022
- __Link to the dataset__: https://www.kaggle.com/datasets/madrasiharish/spotify-2022-sep-6-7
- __Number of observations__: 1066 originally, filtered to 50

This dataset contains multiple tables detailing the 50 most-streamed songs from the year of 2022. The data is drawn from the listening metrics of approximately 50 countries, but for the purposes of this analysis the data was filtered to only contain data from the United States in 2022.

- __Dataset Name__: Consumer Confidence Index
- __Link to the dataset__: https://data.oecd.org/leadind/consumer-confidence-index-cci.htm
- __Number of observations__: 112 originally, filtered to 55

This dataset tracks changes in consumer confidence levels across approximately 30 countries and a time period of 9 years. Consumer confidence is defined as a predictive measure of one's financial situation, taking into account factors such as unemployment sentiments, countrywide economic trends, and perceived capability of individual financial savings. Consumer confidence values below a score of 100 are interpreted by the creators of the dataset to indicate a pessimistic attitude towards future developments in the economy.

In keeping with the US-centric data collected from the earlier Spotify datasets, the results of this dataset were filtered and restricted to only contain monthly consumer confidence ratings from 2012 until 2022 in the United States.

# Combining Datasets

Due to the unique schema associated with each of the collected Spotify datasets, our team first had to tidy each set to abide by a uniform schema before attempting to proceed with our analysis. Inherently, almost every song-related table had different column labels and even different scales for the numerical valence and energy values, necessitating a cleaning method that provided a uniform schema for the data. Our cleaning strategy is detailed below, but in summary, the following steps were undertaken with slight deviations in steps depending on the presentation of the original data:

1. Data from each Spotify table is ensured to have only the 50 most-streamed songs from its respective year. In the event that there are greater than 50 songs, rows are removed from the original dataset until only the top 50 remain.
2. Columns unnecessary for analysis are removed. Necessary columns are detailed in the description of the first Spotify dataset.
3. Column names are refactored to abide by a single schema. These names include "Track Name", "Artist", "Year", "BPM", "Valence", and "Energy"
4. Columns are reordered in keeping with single schema.
5. Situationally, numerical valence and energy values are refactored to fall within an acceptable range of 0 and 1 inclusive.

# Setup

In [1]:
# import pandas library
import pandas as pd

!pip install openpyxl
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /home/ealiu/.local/lib/python3.9/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /home/ealiu/.local/lib/python3.9/site-packages (from openpyxl) (1.1.0)

# Data Cleaning

__Steps Implemented Below:__

- Load a CSV file of data pertaining to the top songs from 2010-2018
- Drop 2012 and 2019 data with insufficient number of songs
- Filter the data to contain needed columns (Artist/Track Name, Year, BPM, Valence, and Energy)
- Rename columns

In [2]:
#Load a csv file of data
temp = pd.read_csv('top10s.csv', encoding='latin-1')

#Drop 2012 and 2019 data with insufficient number of songs
temp = temp[temp.year != 2012]
temp = temp[temp.year != 2019]

top_50_by_year = None

initiated = False

for i in range(6):
    current_year = temp[temp.year == (2013 + i)]
    current_year = current_year.iloc[:-(current_year.shape[0] - 50)]
    
    if(not initiated):
        top_50_by_year = current_year
        initiated = True
    else:
        top_50_by_year = pd.concat([top_50_by_year, current_year])
        
top_50_by_year = top_50_by_year.reset_index()

del top_50_by_year['index']
del top_50_by_year['Unnamed: 0']

__Steps Implemented Below:__

> - Load CSV files of data pertaining to top songs in 2012, 2019, and 2020-2022
> - Filter our data files to include needed columns (Artist/Track Name, Year, BPM, Valence, and Energy)
> - Rename the titles of these respective columns in order to keep our data tidy

In [3]:
# filtering the data to only include certain columns (title, artist, bpm, valence, energy)
top_50_by_year = top_50_by_year[['title', 'artist', 'year', 'bpm', 'val', 'nrgy']]
top_50_by_year

# renaming the title of each column to keep data consistent and tidy
top_50_by_year = top_50_by_year.rename({'title' : 'Track Name', 'artist' : 'Artist', 'year': 'Year', 'bpm': 'BPM' , 'val': 'Valence' , 'nrgy': 'Energy'}, axis = 'columns')
top_50_by_year

top_50_by_year['Valence'] = top_50_by_year['Valence'].div(100)
top_50_by_year['Energy'] = top_50_by_year['Energy'].div(100)

top_50_by_year

,Track Name,Artist,Year,BPM,Valence,Energy
0,Underneath the Tree,Kelly Clarkson,2013,160,0.69,0.81
1,Wake Me Up,Avicii,2013,124,0.64,0.78
2,Story of My Life,One Direction,2013,121,0.29,0.66
3,Just Give Me a Reason (feat. Nate Ruess),P!nk,2013,95,0.44,0.55
4,Hall of Fame,The Script,2013,85,0.63,0.87
...,...,...,...,...,...,...
295,Want To,Dua Lipa,2018,92,0.32,0.69
296,What I Need (feat. Kehlani),Hayley Kiyoko,2018,104,0.41,0.79
297,Wait,Maroon 5,2018,126,0.45,0.60
298,What About Us,P!nk,2018,114,0.19,0.59
299,Kissing Strangers,DNCE,2018,120,0.86,0.74

In [4]:
# Load a csv file of data
top_50_2012 = pd.read_csv('spotifytoptracks2012.csv', encoding = "ISO-8859-1")
top_50_2012 = top_50_2012[top_50_2012.year == 2012]
top_50_2012 = top_50_2012.iloc[:-(top_50_2012.shape[0] - 50)]
top_50_2012 = top_50_2012[['artist', 'song', 'year', 'energy', 'tempo', 'valence']]
top_50_2012 = top_50_2012.rename({'artist': 'Artist', 'song': 'Track Name', 'year': 'Year', 'energy': 'Energy', 'tempo': 'BPM', 'valence': 'Valence'}, axis = 'columns')
top_50_2012 = top_50_2012[['Track Name', 'Artist', 'Year', 'BPM', 'Valence', 'Energy']]

# Load a csv file of data
top_50_2019 = pd.read_csv('spotifytoptracks2019.csv', encoding = "ISO-8859-1")
top_50_2019 = top_50_2019[['Artist.Name', 'Track.Name', 'Energy', 'Beats.Per.Minute', 'Valence.']]
top_50_2019 = top_50_2019.rename({'Artist.Name': 'Artist', 'Track.Name': 'Track Name', 'Beats.Per.Minute': 'BPM', 'Valence.': 'Valence'}, axis = 'columns')
top_50_2019 = top_50_2019[['Track Name', 'Artist', 'BPM', 'Valence', 'Energy']]
top_50_2019['Valence'] = top_50_2019['Valence'].div(100)
top_50_2019['Energy'] = top_50_2019['Energy'].div(100)
top_50_2019.insert(2, 'Year', 2019)

# Load a csv file of data
top_50_2020 = pd.read_csv('spotifytoptracks2020.csv')

# filtering the data to only include certain columns (artist, track_name, energy, tempo, valence)
top_50_2020 = top_50_2020[['artist', 'track_name', 'energy', 'tempo', 'valence']]

# renaming the title of each column to keep data consistent and tidy
top_50_2020 = top_50_2020.rename({'artist': 'Artist', 'track_name': 'Track Name', 'energy': 'Energy', 'tempo': 'BPM', 'valence': 'Valence'}, axis = 'columns')

# reordering the columns to match column order of other datasets - maintain consistency
top_50_2020 = top_50_2020[['Track Name', 'Artist', 'BPM', 'Valence', 'Energy']]

top_50_2020.insert(2, 'Year', 2020)

# Load a csv file of data
top_50_2021 = pd.read_csv('spotifytoptracks2021.csv')

# renaming the title of each column to keep data consistent and tidy
top_50_2021 = top_50_2021.rename({'artist_name': 'Artist', 'track_name': 'Track Name', 'energy': 'Energy', 'tempo': 'BPM', 'valence': 'Valence'}, axis = 'columns')

# filtering the data to only include certain columns (artist, track name, energy, valence, BPM)
top_50_2021 = top_50_2021[['Artist', 'Track Name', 'Energy', 'Valence', 'BPM']]

# reordering the columns to match column order of other datasets - maintain consistency
top_50_2021 = top_50_2021[['Track Name', 'Artist', 'BPM', 'Valence', 'Energy']]

top_50_2021.insert(2, 'Year', 2021)

# Load a csv file of data
top_50_2022 = pd.read_excel('Spotify.xlsx', sheet_name = 'Top50USA')

# renaming the title of each column to keep data consistent and tidy
top_50_2022 = top_50_2022.rename({'artist': 'Artist', 'name': 'Track Name', 'energy': 'Energy', 'tempo': 'BPM', 'valence': 'Valence'}, axis = 'columns')

# reordering the columns to match column order of other datasets - maintain consistency
top_50_2022 = top_50_2022[['Track Name', 'Artist', 'BPM', 'Valence', 'Energy']]

top_50_2022.insert(2, 'Year', 2022)

In [5]:
top_50_by_year = pd.concat([top_50_2012, top_50_by_year, top_50_2019, top_50_2020, top_50_2021, top_50_2022])
top_50_by_year = top_50_by_year.reset_index(drop=True)

top_50_by_year

,Track Name,Artist,Year,BPM,Valence,Energy
0,Crossroads - Radio Edit,Blazin' Squad,2012,144.188,0.502,0.746
1,Let Me Go,3 Doors Down,2012,92.004,0.491,0.863
2,Something Kinda Ooooh,Girls Aloud,2012,131.925,0.879,0.908
3,Let Me Think About It,Ida Corr,2012,129.026,0.715,0.754
4,California Gurls,Katy Perry,2012,125.014,0.425,0.754
...,...,...,...,...,...,...
545,BREAK MY SOUL,BeyoncÃ©,2022,114.942,0.864,0.887
546,DespuÃ©s de la Playa,Bad Bunny,2022,78.293,0.607,0.903
547,She Had Me At Heads Carolina,Cole Swindell,2022,134.944,0.722,0.912
548,Static,Steve Lacy,2022,79.001,0.215,0.305
549,Wasted On You,Morgan Wallen,2022,196.000,0.252,0.657

__Steps Implemented Below:__

> - Load CSV file of data containing consumer confidence reports from 2018-2022
> - Filter this data to only include rows pertaining to the United States
> - Further filter rows to only contain columns with info about location, time, and value
> - Rename column titles to keep data tidy

In [6]:
# Load a csv file of data
consumer_report = pd.read_csv('cc_usa.csv')
consumer_report

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
0,OECD,CCI,AMPLITUD,LTRENDIDX,M,2014-01,99.57079,NaN
1,OECD,CCI,AMPLITUD,LTRENDIDX,M,2014-02,99.62329,NaN
2,OECD,CCI,AMPLITUD,LTRENDIDX,M,2014-03,99.71998,NaN
3,OECD,CCI,AMPLITUD,LTRENDIDX,M,2014-04,99.83662,NaN
4,OECD,CCI,AMPLITUD,LTRENDIDX,M,2014-05,99.89146,NaN
...,...,...,...,...,...,...,...,...
207,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-06,96.02940,NaN
208,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-07,95.99727,NaN
209,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-08,96.27924,NaN
210,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-09,96.55611,NaN
211,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-10,96.79916,NaN

In [7]:
# filter data to only include rows where the LOCATION is the 'USA'
consumer_report = consumer_report[consumer_report.LOCATION == 'USA']
consumer_report

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
106,USA,CCI,AMPLITUD,LTRENDIDX,M,2014-01,99.34292,NaN
107,USA,CCI,AMPLITUD,LTRENDIDX,M,2014-02,99.41605,NaN
108,USA,CCI,AMPLITUD,LTRENDIDX,M,2014-03,99.44971,NaN
109,USA,CCI,AMPLITUD,LTRENDIDX,M,2014-04,99.52591,NaN
110,USA,CCI,AMPLITUD,LTRENDIDX,M,2014-05,99.51170,NaN
...,...,...,...,...,...,...,...,...
207,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-06,96.02940,NaN
208,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-07,95.99727,NaN
209,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-08,96.27924,NaN
210,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-09,96.55611,NaN
211,USA,CCI,AMPLITUD,LTRENDIDX,M,2022-10,96.79916,NaN

In [8]:
# filtering the data to only include certain columns (location, time, value)
consumer_report = consumer_report[['LOCATION', 'TIME', 'Value']]
consumer_report

    LOCATION     TIME     Value
106      USA  2014-01  99.34292
107      USA  2014-02  99.41605
108      USA  2014-03  99.44971
109      USA  2014-04  99.52591
110      USA  2014-05  99.51170
..       ...      ...       ...
207      USA  2022-06  96.02940
208      USA  2022-07  95.99727
209      USA  2022-08  96.27924
210      USA  2022-09  96.55611
211      USA  2022-10  96.79916

[106 rows x 3 columns]

In [10]:
# renaming the title of each column to keep data consistent and tidy
consumer_report = consumer_report.rename({'LOCATION': 'Location', 'TIME': 'Time'}, axis = 'columns')
consumer_report = consumer_report.reset_index(drop = True)

Location  Time     Value
USA       2014-01  99.34292     1
          2020-08  98.71681     1
          2020-06  98.49448     1
          2020-05  98.54501     1
          2020-04  99.05240     1
                               ..
          2016-09  100.45110    1
          2016-08  100.47100    1
          2016-07  100.58120    1
          2016-06  100.73370    1
          2022-10  96.79916     1
Length: 106, dtype: int64

In [11]:
# convert time values to datetime objects
consumer_report['Time'] =  pd.to_datetime(consumer_report['Time'])
consumer_report['Time']

0     2014-01-01
1     2014-02-01
2     2014-03-01
3     2014-04-01
4     2014-05-01
         ...
101   2022-06-01
102   2022-07-01
103   2022-08-01
104   2022-09-01
105   2022-10-01
Name: Time, Length: 106, dtype: datetime64[ns]